### ISSUE TITLE
uncaught php error TwilioMinimal.php

### ISSUE THREAD

**Issue by Jeff-lansidel** [nikopeikrishvili/TwilioMinimal#1]
Hi thanks for creating this class for Twilio! below is an error thrown and I do realize that this is a trial twilio account but is the app supposed to return error codes back to $twilio->send request? 

PHP Fatal error:  Uncaught NikoPeikrishvili\\TwilioMinimal\\Exceptions\\UnableToSendMessageException: Client error: `POST https://api.twilio.com/2010-04-01/Accounts/xxxxxxxxxxxxxxxxxx/Messages.json` resulted in a `400 BAD REQUEST` response:\n{"code": 21608, "message": "The number  is unverified. Trial accounts cannot send messages to unverified numbers; verify (truncated...)\n in /var/www/texting/vendor/nikopeikrishvili/twiliominimal/src/TwilioMinimal.php:45\nStack trace:\n#0 /var/www/texting/text_day_scheduled.php(102): NikoPeikrishvili\\TwilioMinimal\\TwilioMinimal->send('+1xxxxxxxxxx', 'Testing Messge ...')\n#1 {main}\n  thrown in /var/www/texting/vendor/nikopeikrishvili/twiliominimal/src/TwilioMinimal.php on line 45

**Comment by nikopeikrishvili** [comment]
Hello Jeff,
thank you for a message,

you need to surround sending with try-catch
```php
try
{
$twilio->send("+00000000000", "Messge body");
}
catch(Exception $e)
{
   // message didnt sended $e->getMessage() will contain error reason
}
```
